sudo: false

matrix:
  include:
    - env: CABALVER=1.18 GHCVER=7.8.4
      addons: {apt: {packages: [ghc-7.8.4], sources: [hvr-ghc]}}
    - env: CABALVER=1.22 GHCVER=7.10.3
      addons: {apt: {packages: [ghc-7.10.3],sources: [hvr-ghc]}}
    - env: CABALVER=1.24 GHCVER=8.0.2
      addons: {apt: {packages: [ghc-8.0.2],sources: [hvr-ghc]}}
    - env: CABALVER=2.0 GHCVER=8.2.1
      addons: {apt: {packages: [ghc-8.2.1],sources: [hvr-ghc]}}
    - env: CABALVER=head GHCVER=head
      addons: {apt: {packages: [ghc-head],  sources: [hvr-ghc]}}

before_install:
 - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH

install:
 - echo "$(ghc --version)"

script:
 - ghc --show-options | grep '^-X' | sed 's/-X//' | grep -v "^No"
 - ghc --show-options | grep '^-X' | sed 's/-X//' | grep -v "^No" > ghc-${GHCVER}.txt
